# Generated by Django 4.2.1 on 2023-06-02 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(db_column='event_id', primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Whole Day', 'Whole Day'), ('Half Day', 'Half Day')], max_length=15)),
                ('half_day_type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=15)),
                ('eventdate', models.DateField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idnotification', models.AutoField(db_column='idnotification', primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('extname', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('BSIT', 'BSIT'), ('BSCS', 'BSCS'), ('BSES', 'BSES'), ('BSMB', 'BSMB'), ('BSMRB', 'BSMRB')], max_length=10)),
                ('year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth year')], max_length=15)),
                ('block', models.CharField(choices=[('Block 1', 'Block 1'), ('Block 2', 'Block 2'), ('Block 3', 'Block 3'), ('Block 4', 'Block 4'), ('Block 5', 'Block 5')], max_length=15)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='NotifStudents',
            fields=[
                ('notifstudents_id', models.AutoField(db_column='notifstudents_id', primary_key=True, serialize=False)),
                ('notif_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.notification')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.student')),
            ],
            options={
                'db_table': 'notifstudents',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.AutoField(db_column='attendanceid', primary_key=True, serialize=False)),
                ('timein_am', models.DateField(blank=True, null=True)),
                ('timeout_am', models.DateField(blank=True, null=True)),
                ('timein_pm', models.DateField(blank=True, null=True)),
                ('timeout_pm', models.DateField(blank=True, null=True)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.event')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.student')),
            ],
            options={
                'db_table': 'myattendance',
            },
        ),
    ]
