# Generated by Django 4.2.1 on 2023-06-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('eventattendanceid', models.AutoField(db_column='eventattendanceid', primary_key=True, serialize=False)),
                ('timein_no', models.IntegerField()),
                ('timeout_no', models.IntegerField()),
                ('event_total_timein', models.IntegerField()),
                ('event_total_timeout', models.IntegerField()),
                ('event_total_absents', models.IntegerField()),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.event')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.student')),
            ],
            options={
                'db_table': 'eventattendance',
            },
        ),
    ]
